routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('lang/{locale}', function ($locale) {
    Session::put('locale', $locale);
    return redirect()->back();
});


Auth::routes();

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('companies', 'CompanyController')->middleware('auth');
Route::resource('employees', 'EmployController')->middleware('auth');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    //
     /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'companies';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name','email','logo'];

     /**
     * Get the Employ for the Company.
     */
    public function employees()
    {
        return $this->hasMany('App\Employ');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CompanyRequest;
use App\Http\Requests\EditCompanyRequest;
use App\Company;
use Illuminate\Support\Facades\Mail;
use App\Mail\SendMail;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $companies = Company::latest()->paginate(10);
        return view('company.index', compact('companies'))
            ->with('i', (request()->input('page', 1) - 1) * 10);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyRequest $request)
    {
      // dd($request);
        if($request->hasFile('logo')){
            $extension =$request->file("logo")->getClientOriginalExtension();
            
            $fileNameStore=$request->input('name').'_'.time().'.'.$extension;
            
            $path=$request->file("logo")->storeAs('public/logo', $fileNameStore);            
        }
        else{
            $fileNameStore='avatar.jpg';
        }
        $company = new Company;
        $company->name = $request->input('name');
        $company->email = $request->input('email');
        $company->logo = $fileNameStore;
        $company->save();

        Mail::to('admin@admin.com')->send(new SendMail($company));
        return redirect()->route('companies.index')
          ->with('success', 'Company created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = Company::find($id);
        return view('company.show',compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::find($id);
        return view('company.edit',compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditCompanyRequest $request, $id)
    {
       // dd($request);
        $company = Company::find($id);
        if ($request->hasFile('logo')) {
            $extension = $request->file("logo")->getClientOriginalExtension();
            $fileNameStore = $request->input('name') . '_' . time() . '.' . $extension;
            $path = $request->file("logo")->storeAs('public/logo', $fileNameStore);
        }else{
            $fileNameStore=$company->logo;
        }
        //dd($request->all());
        $company = Company::find($id);

        $company->name = $request->name;
        $company->email = $request->email;
        $company->logo = $fileNameStore;
        $company->save();
        return redirect()->route('companies.index')
          ->with('success', 'company updated successfully');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Company::find($id)->delete();
        return redirect()->route('companies.index')
            ->with('success', 'company deleted successfully');

    }
}

resources/views/Company/edit.blade.php
@extends('layouts.app')
 
@section('content')

<div class="container">
	<div class="row">
	    <div class="col-lg-12 margin-tb">
	        <div class="pull-left">
                <h2>{{ __('site.Edit')}}  [{{ $company->name }} ] </h2>
                <hr>
	        </div>
	    </div>
	</div>
	@if (count($errors) > 0)
		<div class="alert alert-danger">
			<strong>Warning!!</strong> There were some problems with your input.<br><br>
			<ul>
				@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div>
	@endif
    {!! Form::model($company, ['method' => 'PATCH','route' => ['companies.update', $company->id],'enctype'=>'multipart/form-data']) !!}
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>{{ __('site.Name')}}:</strong>
                {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>{{ __('site.Email')}}:</strong>
                {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 p-3">
            <div class="form-group">
                <strong>{{ __('site.Logo')}}:</strong>
                {!! Form::file('logo', null, array('placeholder' => 'Logo','class' => 'form-control')) !!}
        </div>
         @isset($company->logo)
            <img alt="{{ $company->name }}" src="{{ asset('/storage/logo/'.$company->logo) }}"  class="rounded-circle " style="height: 134px;">
         @endisset

        
       {{-- </div> --}}
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
				<button type="submit" class="btn btn-primary">{{ __('site.Submit')}}</button>
                <a class="btn btn-primary" href="{{ route('companies.index') }}">{{ __('site.Back')}}</a>

        </div>
	</div>
    {!! Form::close() !!}
</div>
@endsection

resources/views/Company/index.blade.php
@extends('layouts.app')
 
@section('content')
<div class="container">

    <div class="row">
        <div class="col-lg-12">
            <div class="pull-left">
                <h2>{{ __('site.Companies')}}</h2>
                <hr>
            </div>
            <div class="pull-right text-md-right">
                <a class="btn btn-success" href="{{ route('companies.create') }}"> {{ __('site.Add New company')}}</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <div class="row">
        <div class="col-lg-12 table-responsive">
            <table class="table table-bordered ">
                <tr>
                    <th>{{ __('site.No')}}</th>
                    <th width="80px">{{ __('site.Logo')}}</th>
                    <th>{{ __('site.Name')}}</th>
                    <th>{{ __('site.Email')}}</th>
                    <th width="280px">{{ __('site.Action')}}</th>
                </tr>
                @foreach ($companies as $company)
                <tr>
                    <td>{{ ++$i }}</td>
                    <td><img alt="{{ $company->name }}" src="{{ asset('/storage/logo/'.$company->logo) }}"  class="rounded-circle " style="height: 60px;width: 36px;"></td>
                    <td>{{ $company->name }}</td>
                    <td>{{ $company->email }}</td>
                    <td>
                        <a class="btn btn-info" href="{{ route('companies.show',$company->id) }}">{{ __('site.Show')}}</a>
        
                        <a class="btn btn-primary" href="{{ route('companies.edit',$company->id) }}">{{ __('site.Edit')}}</a>
                        <form action="{{ route('companies.destroy',$company->id) }}" method="POST" style='display:inline'>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">{{ __('site.Delete')}}</button>
                        </form> 
                    </td>
                </tr>
                @endforeach
            </table>
        </div>
    </div>
    {!! $companies->render() !!} 
</div>
@endsection

resources/views/Company/show.blade.php
@extends('layouts.app')
 
@section('content')
<div class="container">
	<div class="row">
	    <div class="col-lg-12 margin-tb">
	        <div class="pull-left">
                <h2> {{ __('site.Show')}} [{{ $company->name }} ]  </h2>
                <hr>
	        </div>
	        
	    </div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>{{ __('site.Name')}}:</strong>
                {{ $company->name }}
            </div>
            <div class="form-group">
                <strong>{{ __('site.Email')}}:</strong>
                {{ $company->email }}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>{{ __('site.Logo')}}:</strong>
                <img  alt="{{ $company->name }}" src="{{ asset('/storage/logo/'.$company->logo) }}"  class="rounded-circle" style="height: 134px;">
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <a class="btn btn-primary" href="{{ route('companies.index') }}">{{ __('site.Back')}}</a>
        </div>
    </div>
</div>
@endsection