routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('lang/{locale}', function ($locale) {
    Session::put('locale', $locale);
    return redirect()->back();
});


Auth::routes();

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('companies', 'CompanyController')->middleware('auth');
Route::resource('employees', 'EmployController')->middleware('auth');

app/Employ.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employ extends Model
{
    //
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'employees';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['first_name','last_name','email','phone','company_id'];

    /**
     * Get the Company that owns the Employ.
     */
    public function companies()
    {
        return $this->belongsTo('App\Company', 'company_id');
    }
}

app/Http/Controllers/EmployController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Employ;
use App\Company;
use App\Http\Requests\EmployRequest;
use App\http\Requests\EditEmployRequest;

class EmployController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $employees = Employ::latest()->paginate(10);

        return view('employ.index', compact('employees'))
            ->with('i', (request()->input('page', 1) - 1) * 10);

        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         $companies = Company::pluck('name', 'id');

        return view('employ.create',compact('companies'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployRequest $request)
    {
        //
        $employ = new Employ;
        $employ->first_name = $request->first_name;
        $employ->last_name = $request->last_name;
        $employ->email = $request->email;
        $employ->phone=$request->phone;
        $employ->company_id = $request->company_id;
        $employ->save();
        return redirect()->route('employees.index')
            ->with('success', 'Employee Added successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $employ = Employ::find($id);
        return view('employ.show',compact('employ'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $employee = Employ::find($id);
        $companies = Company::pluck('name', 'id');
        return view('employ.edit', compact('employee', 'companies'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditEmployRequest $request, $id)
    {
        //
        //dd($request->all());
        $employ = Employ::find($id);
        $employ->first_name = $request->first_name;
        $employ->last_name = $request->last_name;
        $employ->email = $request->email;
        $employ->phone = $request->phone;
        $employ->company_id = $request->company_id;
        $employ->save();
        return redirect()->route('employees.index')
            ->with('success', 'Employee Updated successfully');

    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Employ::find($id)->delete();
        return redirect()->route('employees.index')
          ->with('success', 'Employee deleted successfully');

    }
}

resources/views/Employ/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
   <div class="row">
       <div class="col-lg-12 margin-tb">
           <div class="pull-left">
               <h2>{{ __('site.Add New Employ')}}</h2>
                <hr>

           </div>
           
       </div>
   </div>
   @if (count($errors) > 0)
       <div class="alert alert-danger">
           <strong>Whoops!</strong> There were some problems with your input.<br><br>
           <ul>
               @foreach ($errors->all() as $error)
                   <li>{{ $error }}</li>
               @endforeach
           </ul>
       </div>
   @endif
   {!! Form::open(array('route' => 'employees.store','method'=>'Post','enctype'=>'multipart/form-data')) !!}
   
   <div class="row">
       <div class="col-xs-12 col-sm-12 col-md-6">
           <div class="form-group">
               <strong>{{ __('site.First Name')}}:</strong>
                {!! Form::text('first_name', null, array('placeholder' => 'First Name','class' => 'form-control')) !!}
           </div>
       </div>
       <div class="col-xs-12 col-sm-12 col-md-6">
           <div class="form-group">
               <strong>{{ __('site.Last Name')}}:</strong>
                {!! Form::text('last_name', null, array('placeholder' => 'Last Name','class' => 'form-control')) !!}
           </div>
       </div>
       <div class="col-xs-12 col-sm-12 col-md-6">
           <div class="form-group">
               <strong>{{ __('site.Email')}}:</strong>
                {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
           </div>
       </div>
       <div class="col-xs-12 col-sm-12 col-md-6">
           <div class="form-group">
               <strong>{{ __('site.Phone')}}:</strong>
                {!! Form::text('phone', null, array('placeholder' => 'Phone','class' => 'form-control')) !!}
           </div>
       </div>
       <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>{{ __('site.Company')}}</strong>
                {!! Form::select('company_id', $companies,[], array('class' => 'form-control')) !!}

            </div>
       </div>

       
       <div class="col-xs-12 col-sm-12 col-md-12 text-center">
               <button type="submit" class="btn btn-primary">{{ __('site.Submit')}}</button>
                <a class="btn btn-primary" href="{{ route('employees.index') }}">{{ __('site.Back')}}</a>
       </div>
   </div>
   {!! Form::close() !!}
</div>
@endsection

resources/views/Employ/edit.blade.php
@extends('layouts.app')
 
@section('content')

<div class="container">
	<div class="row">
	    <div class="col-lg-12 margin-tb">
	        <div class="pull-left">
                <h2>{{ __('site.Edit')}}   [{{ $employee->first_name }}  {{ $employee->last_name }} ]</h2>
                <hr>

	        </div>
	    </div>
	</div>
	@if (count($errors) > 0)
		<div class="alert alert-danger">
			<strong>Warning!!</strong> There were some problems with your input.<br><br>
			<ul>
				@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div>
	@endif
    {!! Form::model($employee, ['method' => 'PATCH','route' => ['employees.update', $employee->id],'enctype'=>'multipart/form-data']) !!}
	<div class="row">
		 <div class="col-xs-12 col-sm-12 col-md-6">
           <div class="form-group">
               <strong>{{ __('site.First Name')}}:</strong>
                {!! Form::text('first_name', null, array('placeholder' => 'First Name','class' => 'form-control')) !!}
           </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>{{ __('site.Last Name')}}:</strong>
                    {!! Form::text('last_name', null, array('placeholder' => 'Last Name','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>{{ __('site.Email')}}:</strong>
                    {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>{{ __('site.Phone')}}:</strong>
                    {!! Form::text('phone', null, array('placeholder' => 'Phone','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>{{ __('site.Company')}}</strong>
                    {!! Form::select('company_id', $companies,$employee->company_id, array('class' => 'form-control')) !!}

                </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
				<button type="submit" class="btn btn-primary">{{ __('site.Submit')}}</button>
                <a class="btn btn-primary" href="{{ route('employees.index') }}"> {{ __('site.Back')}}</a>

        </div>
	</div>
    {!! Form::close() !!}
</div>
@endsection

resources/views/Employ/index.blade.php
@extends('layouts.app')
 
@section('content')
<div class="container">

    <div class="row">
        <div class="col-lg-12">
            <div class="pull-left">
                <h2>{{ __('site.Employees')}}</h2>
                <hr>
            </div>
            <div class="pull-right p-2">
                <a class="btn btn-success" href="{{ route('employees.create') }}"> {{ __('site.Add New Employ')}}</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <div class="row">
        <div class="col-lg-12 table-responsive">
            <table class="table table-bordered table-responsive">
                <tr>
                    <th>{{ __('site.No')}}</th>
                    <th>{{ __('site.First Name')}}</th>
                     <th>{{ __('site.Last Name')}}</th>
                    <th>{{ __('site.Email')}}</th>
                    <th>{{ __('site.Phone')}}</th>
                    <th>{{ __('site.Company')}}</th>
                    <th width="280px">{{ __('site.Action')}}</th>
                </tr>
                @foreach ($employees as $employ)
                <tr>
                    <td>{{ ++$i }}</td>
                    <td>{{ $employ->first_name }} </td>
                    <td> {{ $employ->last_name }}</td>
                    <td>{{ $employ->email }}</td>
                    <td>{{ $employ->phone }}</td>
                    <td>
                        <a class="txtlink" href="{{ route('companies.show',$employ->company_id) }}">{{App\Company::find( $employ->company_id)->name}}</a>
                    </td>
                    <td>
        
                        <a class="btn btn-info" href="{{ route('employees.show',$employ->id) }}">{{ __('site.Show')}}</a>
        
                        <a class="btn btn-primary" href="{{ route('employees.edit',$employ->id) }}">{{ __('site.Edit')}}</a>
                        <form action="{{ route('employees.destroy',$employ->id) }}" method="POST" style='display:inline'>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">{{ __('site.Delete')}}</button>
                        </form> 
                    </td>
                </tr>
                @endforeach
            </table>
        </div>
    </div>
    {!! $employees->render() !!} 
</div>
@endsection

resources/views/Employ/show.blade.php
@extends('layouts.app')
 
@section('content')
<div class="container">
	<div class="row">
	    <div class="col-lg-12 margin-tb">
	        <div class="pull-left">
                <h2> {{ __('site.Show')}}  [{{ $employ->first_name }}  {{ $employ->last_name }} ]  </h2>
                 <hr>
	        </div>
	        
	    </div>
    </div>
   
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong> {{ __('site.First Name')}}:</strong>
               
                {{ $employ->first_name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>{{ __('site.Last Name')}}:</strong>
              
                {{ $employ->last_name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>{{ __('site.Email')}}:</strong>
                
                {{ $employ->email }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>{{ __('site.Phone')}}:</strong>
               
                {{ $employ->phone }}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>{{ __('site.Company')}}:</strong>
                 <a class="txtlink" href="{{ route('companies.show',$employ->company_id) }}">{{App\Company::find( $employ->company_id)->name}}</a>
            </div>
        </div>
         
         <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <a class="btn btn-primary" href="{{ route('employees.index') }}">{{ __('site.Back')}}</a>
        </div>
    </div>
</div>
@endsection